### PR TITLE
importer: add default value to numeric fields

### LINKED ISSUE #79: Import: optional default value for numeric fields for empty entries.

### PR DESCRIPTION
**Pull request by clyyuanzi-london**
fix #79

### CODE REVIEW

**Comment by atbenmurray** [comment]
Can I suggest that the default value be treated as a numeric value as early as possible? It can be specified in json as a numeric type and json will load it as such, no?

**Comment by clyyuanzi-london** [comment]
just updated the 'default' to 'invalid_value', and also specified it as a numeric type in JSON.

**Comment by atbenmurray** [comment]
This is looking very good. The only extra thing that we discussed at the time was whether we want to have some convenience notation for ints and floats. "min", "max", for example. If those strings are read by the schema, we automatically substitute in the appropriate min or max value for that datatype. Do you want to do that as part of this or as a separate piece of work?

**Comment by clyyuanzi-london** [comment]
I'll try to do it as part of this PR.

**Comment by clyyuanzi-london** [comment]
just added notation min/max to default invalid_value

**Review by atbenmurray — APPROVED** [review]

**Pull request merged**
