### PR TITLE
CSV Reader Optimization using njit (WIP)

### PR DESCRIPTION
**Pull request by clyyuanzi-london**
Aiming at optimizing the CSV reader, so far the code works but I have not been able to produce performance improvements using njit over the built-in CSV reader.

These are the current benchmarks: 

Original csv reader took 0.00013589859008789062 s
(njit) FAST Open file read lines took 2.1738438606262207 s

Looking for feedback on how I can further improve the code to increase performance

Note, this is just a test file (with some sample data), when code is optimized I will refactor the code.

### CODE REVIEW

**Comment by clyyuanzi-london** [comment]
Just added code so that each function runs once (compile), then measuring the benchmark as Ben suggested.

And here are the updated benchmarks:
- Original csv reader took:: completed in 0.0001709461212158203 seconds
- (njit) FAST Open file read lines took:: completed in 0.0011827945709228516 seconds

The execution time of njit is much faster but still took 10 times longer than the original csv.reader.

**Comment by clyyuanzi-london** [comment]
Updated the output excel (matrix) from string to int tuple, and tested on a larger dataset

Here are the updated benmarks:
Original csv reader took:: completed in 0.007363080978393555 seconds
(njit) FAST Open file read lines took:: completed in 0.08140707015991211 seconds

The execution time of njit is much faster but still took 10 times longer than the original csv.reader.

**Comment by clyyuanzi-london** [comment]
Initialize the column_idx outside of the njit function.

Here are the updated benchmarks:

resources/assessment_input_small_data.csv
Original csv reader took: 0.004989147186279297 seconds
(njit) FAST Open file read lines took:  0.0450439453125 seconds

The execution time of njit still took 10 times longer than the original csv.reader.

**Comment by clyyuanzi-london** [comment]
Upgraded np.fromfile to load the file into byte array, and tested in much larger dataset/

Original csv reader took: 33.60528302192688 seconds
(njit) FAST Open file read lines took: 49.71092772483826 seconds

The execution time of njit is much faster but still took 1.5 times longer than the original csv.reader.

**Comment by clyyuanzi-london** [comment]
Made it work convert the categorical field from bytes to value int within njit function.

Here are the updated benchmarks:
- Original csv reader took: 55.909518003463745s
- (njit) FAST Open file read lines took: 17.328250885009766s seconds

The execution time of njit is much faster (around 3.3 times) faster than the original csv.reader.

**Comment by clyyuanzi-london** [comment]
- replaced padding with concatenation for categorical keys 
- solve a few bugs: (1) deal with the last cell in the last line (2) fix the one missing value between two chunks, etc.


Here are the updated benchmarks on csv data with 50 million lines:
- original csv.reader version took : 108.26102089881897s
- fast njit verion took: 35.37674903869629s

The execution time of njit is around 3.1 times faster than the original csv.reader.

**Comment by clyyuanzi-london** [comment]
Here are the updated benchmarks on csv data with 50 million lines (only selected the numeric field):
(1) using njit function that transform numeric field from indices/values directly, it took 25.760451078414917 seconds
(2) using function that transform numeric field from indices/values to bytes first, it took 109.53480195999146 seconds
(3) Original csv reader, it took 160.3496708869934s 

As we can see, the (1) is much faster, around 6.5 times faster than the original one. 

For (1) I've added the logic that considering power e. And also added unittest that covering cases below:
1.
.1
001
001.0000
1e1
+1e-1

**Review by ericspod — APPROVED** [review]

**Pull request merged**
